---
#  -name: make ec2 up and running
- hosts: demo
  user: root
  become: yes
  connection: ssh
  gather_facts: no

  tasks:
  - name: Copying project 
    copy: src={{PATH_TODO_PLATEFORM}}/backend.zip dest=/home/ec2-user/project

  - name: delete old file
    command: rm -rf backend

  - name: unzip project
    command: unzip /home/ec2-user/project/backend.zip

  - name: rewrite docker file 
    copy: src={{PATH_TODO_PLATEFORM}}/ansible/Dockerfile dest=/home/ec2-user/backend/Dockerfile

  - name: rewrite docker file 
    copy: src={{PATH_TODO_PLATEFORM}}/ansible/script.sh dest=/home/ec2-user/backend/script.sh
  

