---
#  -name: make ec2 up and running
- hosts: demo
  user: root
  become: yes
  connection: ssh
  gather_facts: no

  tasks:


    # - name: Yum repolist for Docker
    #   yum_repository:
    #     name: docker
    #     description: yum repository for docker
    #     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    #     gpgcheck: no

    # - name: Package Installer For Docker
    #   package:
    #     name: docker-ce-3:18.09.1-3.el7
    #     state: present

    # - name: Package Installer For Python3 
    #   package:
    #     name: python3
    #     state: present

    # - name: Installing python library for the Docker Remote API
    #   pip:
    #     name: docker-py

    # - name: Start service docker
    #   service:
    #     name: docker
    #     state: started



  - name: download docker
    command: sudo amazon-linux-extras install docker
    
  - name: service start
    command: sudo service docker start

  - name: service start
    command: sudo usermod -a -G docker ec2-user

  - name: install python
    command: sudo yum -y install python37
    
  - name: install pip
    command: sudo yum -y install python-pip

  - name: install docker py
    command: sudo pip install docker-py

  # - name: install docker compose
  #   command: sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

  # - name: give permission to docker-compose
  #   command: sudo chmod +x /usr/local/bin/docker-compose

