apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SENTRY_DSN: aHR0cHM6Ly9mNjBmZjg5NDAwZGI0YzNkOWNhNzU5M2FkZWUxNmQxMEBvNTIwNzU4LmluZ2VzdC5zZW50cnkuaW8vNTYzMTUzOQ==
  SENDGRID_PASSWORD: U0cuZnlsaEs5QmxSN0d1WENLYlM2U0FaZy5Lb05HN2s1T3RPVDNheW5acVdlU0wzWmN0SGlaVmJlTWViRnp6Vzdad3hv
  
